# list of paths to necessary scripts.json
:dependency_paths:
  - '../mootools-core/Source'  # Mootools Core
  - '../mootools-more/Source'  # Mootools More
  - '../cnetjavascript/Source' # clientcide
  - './Source'                 # This project

# output file path
:build_path: './lib.js'